import attr_img_1 from "../assets/images/p1.png";
import attr_img_2 from "../assets/images/p2.png";

export const products = [
  {
    id: 1,
    name: "Skullcandy - Crusher anc 2 wireless headphones",
    discount: "-50%",
    status: "NEW",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 5,
    avg_rating: 4.8,
    rating_count: 100,
    price_range: "5,000.00৳ - 6,000.00৳",
    actual_price: 4000,
    category: "Headphones",
  },
  {
    id: 2,
    name: "Skullcandy - Crusher anc 2 wireless headphones",
    discount: "-50%",
    status: "NEW",
    popolarity: "Best Seller",
    thumbnail: attr_img_1,
    attribute_images: [
      {
        id: 1,
        default: true,
        image: attr_img_1,
      },
      {
        id: 2,
        default: false,
        image: attr_img_1,
      },
      {
        id: 3,
        default: false,
        image: attr_img_1,
      },
    ],
    rating: 5,
    avg_rating: 4.8,
    rating_count: 100,
    price_range: "5,000.00৳ - 6,000.00৳",
    actual_price: 4000,
    category: "Headphones",
  },

  {
    id: 3,
    name: "Skullcandy - Crusher anc 2 wireless headphones",
    discount: "-50%",
    status: "NEW",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_1,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 5,
    avg_rating: 4.8,
    rating_count: 100,
    price_range: "5,000.00৳ - 6,000.00৳",
    actual_price: 4000,
    category: "Headphones",
  },

  {
    id: 4,
    name: "Skullcandy - Crusher anc 2 wireless headphones",
    discount: "-50%",
    status: "NEW",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_1,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 5,
    avg_rating: 4.8,
    rating_count: 100,
    price_range: "5,000.00৳ - 6,000.00৳",
    actual_price: 4000,
    category: "Headphones",
  },
];

export const categoryProducts = [
  {
    id: 1,
    name: "Skullcandy - Crusher anc 2 wireless headphones",
    discount: "-50%",
    status: "NEW",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 5,
    avg_rating: 4.8,
    rating_count: 100,
    price_range: "5,000.00৳ - 6,000.00৳",
    actual_price: 4000,
    category: "Headphones",
  },
  {
    id: 2,
    name: "AKG Y50 Wireless Headphones",
    discount: "-40%",
    status: "NEW",
    thumbnail: attr_img_1,
    popolarity: "Popular",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 4,
    avg_rating: 4.9,
    rating_count: 95,
    price_range: "3,131.00৳ - 3,697.00৳",
    actual_price: 2807,
    category: "Headphones",
  },
  {
    id: 3,
    name: "Sony MDRZX110NC Noise Cancelling Headphones",
    discount: "-10%",
    status: "NEW",
    thumbnail: attr_img_1,
    popolarity: "Trending",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 5,
    avg_rating: 4.3,
    rating_count: 51,
    price_range: "3,133.00৳ - 3,740.00৳",
    actual_price: 2845,
    category: "Headphones",
  },
  {
    id: 4,
    name: "Sony WH-1000XM4 Wireless Headphones",
    discount: "-30%",
    status: "SALE",
    thumbnail: attr_img_1,
    popolarity: "Popular",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 1,
    avg_rating: 3.6,
    rating_count: 167,
    price_range: "4,543.00৳ - 5,962.00৳",
    actual_price: 3376,
    category: "Headphones",
  },
  {
    id: 5,
    name: "Marshall Monitor Wireless Headphones",
    discount: "-30%",
    status: "HOT",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 4,
    avg_rating: 4.1,
    rating_count: 156,
    price_range: "4,030.00৳ - 4,902.00৳",
    actual_price: 3515,
    category: "Headphones",
  },
  {
    id: 6,
    name: "Plantronics BackBeat Go 810",
    discount: "-10%",
    status: "HOT",
    thumbnail: attr_img_1,
    popolarity: "Trending",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 5,
    avg_rating: 4.3,
    rating_count: 120,
    price_range: "4,669.00৳ - 5,414.00৳",
    actual_price: 2904,
    category: "Headphones",
  },
  {
    id: 7,
    name: "Sennheiser HD 450BT Wireless Headphones",
    discount: "-50%",
    status: "SALE",
    thumbnail: attr_img_1,
    popolarity: "Popular",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 4,
    avg_rating: 4.7,
    rating_count: 92,
    price_range: "4,668.00৳ - 5,201.00৳",
    actual_price: 3716,
    category: "Headphones",
  },
  {
    id: 8,
    name: "AKG Y50 Wireless Headphones",
    discount: "-30%",
    status: "HOT",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 2,
    avg_rating: 4.9,
    rating_count: 14,
    price_range: "3,254.00৳ - 4,626.00৳",
    actual_price: 2881,
    category: "Headphones",
  },
  {
    id: 9,
    name: "Beats Studio3 Wireless Headphones",
    discount: "-30%",
    status: "HOT",
    thumbnail: attr_img_1,
    popolarity: "Trending",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 2,
    avg_rating: 4.9,
    rating_count: 170,
    price_range: "4,920.00৳ - 6,109.00৳",
    actual_price: 3479,
    category: "Headphones",
  },
  {
    id: 10,
    name: "Jabra Elite 85h Wireless Headphones",
    discount: "-30%",
    status: "HOT",
    thumbnail: attr_img_1,
    popolarity: "Popular",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 3,
    avg_rating: 4.2,
    rating_count: 141,
    price_range: "4,230.00৳ - 4,979.00৳",
    actual_price: 3538,
    category: "Headphones",
  },
  {
    id: 11,
    name: "Beats Solo3 Wireless Headphones",
    discount: "-20%",
    status: "SALE",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 3,
    avg_rating: 4.0,
    rating_count: 83,
    price_range: "4,071.00৳ - 5,048.00৳",
    actual_price: 3552,
    category: "Headphones",
  },
  {
    id: 12,
    name: "Jabra Elite 85h Wireless Headphones",
    discount: "-40%",
    status: "NEW",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 2,
    avg_rating: 4.7,
    rating_count: 111,
    price_range: "3,530.00৳ - 4,932.00৳",
    actual_price: 3056,
    category: "Headphones",
  },
  {
    id: 13,
    name: "Apple AirPods Max",
    discount: "-40%",
    status: "NEW",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 1,
    avg_rating: 3.7,
    rating_count: 164,
    price_range: "3,996.00৳ - 4,897.00৳",
    actual_price: 3603,
    category: "Headphones",
  },
  {
    id: 14,
    name: "AKG Y50 Wireless Headphones",
    discount: "-30%",
    status: "NEW",
    thumbnail: attr_img_1,
    popolarity: "Popular",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 5,
    avg_rating: 3.6,
    rating_count: 48,
    price_range: "3,072.00৳ - 3,932.00৳",
    actual_price: 2643,
    category: "Headphones",
  },
  {
    id: 15,
    name: "Skullcandy Crusher Wireless Headphones",
    discount: "-40%",
    status: "NEW",
    thumbnail: attr_img_1,
    popolarity: "Popular",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 1,
    avg_rating: 4.6,
    rating_count: 70,
    price_range: "3,548.00৳ - 4,677.00৳",
    actual_price: 3074,
    category: "Headphones",
  },
  {
    id: 16,
    name: "Beats Solo3 Wireless Headphones",
    discount: "-30%",
    status: "NEW",
    thumbnail: attr_img_1,
    popolarity: "Trending",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 1,
    avg_rating: 3.5,
    rating_count: 36,
    price_range: "4,797.00৳ - 6,149.00৳",
    actual_price: 4182,
    category: "Headphones",
  },
  {
    id: 17,
    name: "JBL Tune 750BTNC Wireless Headphones",
    discount: "-50%",
    status: "SALE",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 5,
    avg_rating: 4.2,
    rating_count: 89,
    price_range: "3,966.00৳ - 5,385.00৳",
    actual_price: 3433,
    category: "Headphones",
  },
  {
    id: 18,
    name: "AKG Y50 Wireless Headphones",
    discount: "-50%",
    status: "HOT",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 1,
    avg_rating: 4.5,
    rating_count: 174,
    price_range: "3,267.00৳ - 4,190.00৳",
    actual_price: 2961,
    category: "Headphones",
  },
  {
    id: 19,
    name: "Beats Studio3 Wireless Headphones",
    discount: "-10%",
    status: "HOT",
    thumbnail: attr_img_1,
    popolarity: "Trending",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 4,
    avg_rating: 4.5,
    rating_count: 187,
    price_range: "4,995.00৳ - 6,122.00৳",
    actual_price: 3143,
    category: "Headphones",
  },
  {
    id: 20,
    name: "Sennheiser Momentum 3 Wireless Headphones",
    discount: "-30%",
    status: "HOT",
    thumbnail: attr_img_1,
    popolarity: "Popular",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 4,
    avg_rating: 3.9,
    rating_count: 15,
    price_range: "4,099.00৳ - 5,549.00৳",
    actual_price: 3109,
    category: "Headphones",
  },
  {
    id: 21,
    name: "Bose SoundLink Around Ear Wireless Headphones II",
    discount: "-10%",
    status: "SALE",
    thumbnail: attr_img_1,
    popolarity: "Best Seller",
    attribute_images: [
      {
        id: 1,
        image: attr_img_1,
      },
      {
        id: 2,
        image: attr_img_2,
      },
      {
        id: 3,
        image: attr_img_1,
      },
    ],
    rating: 3,
    avg_rating: 4.8,
    rating_count: 47,
    price_range: "4,589.00৳ - 5,639.00৳",
    actual_price: 3515,
    category: "Headphones",
  },
];
